In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from mplsoccer import Pitch, 
from pathlib import Path

In [4]:
MATCH_DIR = Path("../data/matches").glob("*/")
MATCH_DIR = sorted(MATCH_DIR)

In [5]:
qualifiers = pd.read_parquet(f"{MATCH_DIR[32]}/qualifiers.parquet")
events = pd.read_parquet(f"{MATCH_DIR[32]}/events.parquet")
meta   = pd.read_parquet(f"{MATCH_DIR[32]}/metadata.parquet")

qualifiers.info(), events.info(), meta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8176 entries, 0 to 8175
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   event_id        8176 non-null   int64
 1   qualifier_id    8176 non-null   int64
 2   qualifier_name  8176 non-null   object
 3   qualifier_desc  8176 non-null   object
 4   value           6666 non-null   object
dtypes: int64(2), object(3)
memory usage: 319.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1740 entries, 0 to 1739
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           1740 non-null   int64
 1   match_id     1740 non-null   object
 2   type_id      1740 non-null   int64
 3   type_name    1740 non-null   object
 4   period_id    1740 non-null   int64
 5   minute       1740 non-null   int64
 6   second       1740 non-null   int64
 7   team_id      1740 non-null   object
 8   player_id    1695 non-null   object
 9   player_name  1695 non-null   object
 10  outcome      1740 non-null   int64
 11  x            1740 non-null   float64
 12  y            1740 non-null   float64
 13  timestamp    1740 non-null   datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), float64(2), int64(6), object(5)
memory usage: 190.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   match_id          1 non-null      object
 1   local_date        1 non-null      object
 2   local_time        1 non-null      object
 3   match_week        1 non-null      object
 4   competition_id    1 non-null      object
 5   competition_name  1 non-null      object
 6   competition_code  1 non-null      object
 7   season            1 non-null      object
 8   home_team_id      1 non-null      object
 9   home_team_name    1 non-null      object
 10  away_team_name    1 non-null      object
 11  away_team_id      1 non-null      object
 12  venue             1 non-null      object
 13  winner            1 non-null      object
 14  match_status      1 non-null      object
 15  goals_home        1 non-null      int64
 16  goals_away        1 non-null      int64
dtypes: int64(2), object(15)
memory usage: 268.0+ bytes

(None, None, None)

In [8]:
shots = events.loc[events["type_name"].isin(["Attempt Saved", "Miss", "Goal","Post"])]

In [ ]:
shot_qualfiers = qualifiers[
    qualifiers["event_id"].isin(shots["id"].unique())
].sort_values(by=["event_id", "qualifier_id"])

,event_id,qualifier_id,qualifier_name,qualifier_desc,value
533,2935136635,18,Out of box centre,Shot zone: central area outside penalty box,None
535,2935136635,20,Right footed,Shot with right foot,None
526,2935136635,22,Regular play,Shot during open play (not from a set piece),None
528,2935136635,29,Assisted,Shot had assist,None
524,2935136635,55,Related event ID,Event ID of the related assist or preceding event,63
530,2935136635,56,Zone,Back/Left/Centre/Right,Center
532,2935136635,84,Close low right,Goal mouth zone: close range low right of GK,None
534,2935136635,102,Goal mouth y coordinate,Y coordinate where the shot crossed or was sav...,42.7
523,2935136635,103,Goal mouth z coordinate,Height (Z) where the shot crossed or was saved...,34.7
529,2935136635,120,Swerve left,Swerve left,None
531,2935136635,215,Individual play,Individual play,None
527,2935136635,230,GK X coordinate,GK position X,98.4
525,2935136635,231,GK Y coordinate,GK position Y,50.4
699,2935138429,17,Box centre,Shot zone: central part of penalty area,None
702,2935138429,20,Right footed,Shot with right foot,None

In [16]:
shots

,id,match_id,type_id,type_name,period_id,minute,second,team_id,player_id,player_name,outcome,x,y,timestamp
114,2935136635,50o32ylys1nykzuao8kko9ams,13,Miss,1,4,22,1r3545b2dzan8yqa80gtmcjch,5606cqx2mlkrp81oe6uh6ghec,C. Talbi,1,80.4,59.1,2026-05-09 14:04:50.116000+00:00
150,2935138429,50o32ylys1nykzuao8kko9ams,15,Attempt Saved,1,5,53,1r3545b2dzan8yqa80gtmcjch,dwnd8j9ok6ncbp69gmchw953o,N. Sadiki,1,84.0,55.7,2026-05-09 14:06:21.602000+00:00
164,2935140027,50o32ylys1nykzuao8kko9ams,13,Miss,1,7,12,1r3545b2dzan8yqa80gtmcjch,2o3bka7gokfjkej1f600ovbo5,O. Alderete,1,91.4,63.6,2026-05-09 14:07:40.225000+00:00
183,2935141847,50o32ylys1nykzuao8kko9ams,13,Miss,1,9,6,6eqit8ye8aomdsrrq0hk3v7gh,didsdryngjutw2x6tpwnnju5m,A. Diallo,1,81.6,41.8,2026-05-09 14:09:34.118000+00:00
191,2935143217,50o32ylys1nykzuao8kko9ams,15,Attempt Saved,1,10,18,1r3545b2dzan8yqa80gtmcjch,9c2i7ddl2uh7kuhwq62klkyui,B. Brobbey,1,93.6,36.8,2026-05-09 14:10:45.640000+00:00
327,2935152671,50o32ylys1nykzuao8kko9ams,15,Attempt Saved,1,18,11,1r3545b2dzan8yqa80gtmcjch,44o5mjglkzqxctz07ust9bcru,E. Le Fée,1,88.9,37.2,2026-05-09 14:18:38.956000+00:00
329,2935152705,50o32ylys1nykzuao8kko9ams,15,Attempt Saved,1,18,12,1r3545b2dzan8yqa80gtmcjch,44o5mjglkzqxctz07ust9bcru,E. Le Fée,1,88.1,39.5,2026-05-09 14:18:40.267000+00:00
405,2935157891,50o32ylys1nykzuao8kko9ams,15,Attempt Saved,1,23,5,1r3545b2dzan8yqa80gtmcjch,4yyekuopwb7otz18rqfgwjht5,L. Geertruida,1,94.9,45.8,2026-05-09 14:23:32.983000+00:00
478,2935163327,50o32ylys1nykzuao8kko9ams,13,Miss,1,27,56,6eqit8ye8aomdsrrq0hk3v7gh,56bidwsegakrtx3z1qbbpnc6i,J. Zirkzee,1,89.5,52.6,2026-05-09 14:28:23.945000+00:00
554,2935167007,50o32ylys1nykzuao8kko9ams,13,Miss,1,31,7,1r3545b2dzan8yqa80gtmcjch,9c2i7ddl2uh7kuhwq62klkyui,B. Brobbey,1,92.1,31.5,2026-05-09 14:31:35.395000+00:00
600,2935169299,50o32ylys1nykzuao8kko9ams,15,Attempt Saved,1,33,6,1r3545b2dzan8yqa80gtmcjch,dwnd8j9ok6ncbp69gmchw953o,N. Sadiki,1,85.0,48.5,2026-05-09 14:33:34.210000+00:00
673,2935175327,50o32ylys1nykzuao8kko9ams,15,Attempt Saved,1,37,59,1r3545b2dzan8yqa80gtmcjch,cfg0ocm0b2icpagbtnzkrihn9,N. Mukiele,1,76.3,36.6,2026-05-09 14:38:27.263000+00:00
804,2935183439,50o32ylys1nykzuao8kko9ams,15,Attempt Saved,1,45,8,6eqit8ye8aomdsrrq0hk3v7gh,9rm3r46uzxlmuqnp0jo4danhm,Matheus Cunha,1,85.2,66.3,2026-05-09 14:45:36.268000+00:00
806,2935183479,50o32ylys1nykzuao8kko9ams,13,Miss,1,45,10,6eqit8ye8aomdsrrq0hk3v7gh,cgm6zre07l5qauif32jtfqsk4,K. Mainoo,1,90.1,47.0,2026-05-09 14:45:38.500000+00:00
927,2935198537,50o32ylys1nykzuao8kko9ams,13,Miss,2,48,54,6eqit8ye8aomdsrrq0hk3v7gh,9rm3r46uzxlmuqnp0jo4danhm,Matheus Cunha,1,71.0,47.4,2026-05-09 15:06:43.182000+00:00
951,2935199711,50o32ylys1nykzuao8kko9ams,15,Attempt Saved,2,50,9,6eqit8ye8aomdsrrq0hk3v7gh,9rm3r46uzxlmuqnp0jo4danhm,Matheus Cunha,1,90.5,62.5,2026-05-09 15:07:58.174000+00:00
974,2935200349,50o32ylys1nykzuao8kko9ams,15,Attempt Saved,2,50,51,6eqit8ye8aomdsrrq0hk3v7gh,3vtjjrqof5z2tjj84ehadqc45,Bruno Fernandes,1,75.2,39.1,2026-05-09 15:08:40.742000+00:00
1179,2935211291,50o32ylys1nykzuao8kko9ams,13,Miss,2,61,38,1r3545b2dzan8yqa80gtmcjch,6264xjr1y00yu7b9j2pknalzp,G. Xhaka,1,75.0,34.2,2026-05-09 15:19:27.671000+00:00
1207,2935212385,50o32ylys1nykzuao8kko9ams,15,Attempt Saved,2,62,42,1r3545b2dzan8yqa80gtmcjch,9c2i7ddl2uh7kuhwq62klkyui,B. Brobbey,1,86.3,51.7,2026-05-09 15:20:30.982000+00:00
1358,2935219877,50o32ylys1nykzuao8kko9ams,14,Post,2,70,40,1r3545b2dzan8yqa80gtmcjch,4yyekuopwb7otz18rqfgwjht5,L. Geertruida,1,80.2,42.5,2026-05-09 15:28:29.289000+00:00
1455,2935224781,50o32ylys1nykzuao8kko9ams,15,Attempt Saved,2,76,16,6eqit8ye8aomdsrrq0hk3v7gh,9rm3r46uzxlmuqnp0jo4danhm,Matheus Cunha,1,77.1,67.1,2026-05-09 15:34:05.440000+00:00
1590,2935232711,50o32ylys1nykzuao8kko9ams,15,Attempt Saved,2,84,34,1r3545b2dzan8yqa80gtmcjch,31foqyshubo5nkh8kdmbjw8kq,T. Hume,1,77.1,47.2,2026-05-09 15:42:23.897000+00:00
1595,2935232929,50o32ylys1nykzuao8kko9ams,13,Miss,2,84,50,1r3545b2dzan8yqa80gtmcjch,44o5mjglkzqxctz07ust9bcru,E. Le Fée,1,75.0,65.8,2026-05-09 15:42:38.977000+00:00
1680,2935238913,50o32ylys1nykzuao8kko9ams,13,Miss,2,90,53,6eqit8ye8aomdsrrq0hk3v7gh,3vtjjrqof5z2tjj84ehadqc45,Bruno Fernandes,1,78.7,31.7,2026-05-09 15:48:42.788000+00:00
1706,2935240349,50o32ylys1nykzuao8kko9ams,15,Attempt Saved,2,92,20,6eqit8ye8aomdsrrq0hk3v7gh,9rm3r46uzxlmuqnp0jo4danhm,Matheus Cunha,1,87.8,59.3,2026-05-09 15:50:09.148000+00:00
1729,2935242097,50o32ylys1nykzuao8kko9ams,15,Attempt Saved,2,94,30,6eqit8ye8aomdsrrq0hk3v7gh,v78uhwxgzojcec8lsdvucusp,B. Mbeumo,1,85.6,38.7,2026-05-09 15:52:19.275000+00:00