In [11]:
import pandas as pd
import matplotlib.pyplot as plt
from mplsoccer import Pitch

In [12]:
matches = pd.read_parquet("../data/match-events/metadata.parquet")

In [13]:
matches[["local_date", "home_team_name", "away_team_name"]].sort_values(by="local_date").shape

(34, 3)

In [14]:
df_events = pd.read_parquet("../data/match-events/events.parquet")

In [15]:
df_events["match_id"].unique().shape

(34,)

In [16]:
df_events["type_name"].unique()

array(['Team set up', 'Start', 'Pass', 'Ball touch', 'Unknown (ID: 83)',
       'Clearance', 'Ball recovery', 'Foul', 'Take On', 'Deleted event',
       'Corner Awarded', 'Aerial', 'Challenge', 'Interception', 'Tackle',
       'Out', 'Blocked Pass', 'Dispossessed', 'Miss', 'Keeper pick-up',
       'Offside Pass', 'Offside provoked', 'Shield ball opp', 'Error',
       'Goal', 'Attempt Saved', 'Save', 'Post',
       'Injury Time Announcement', 'End', 'Player off', 'Player on',
       'Start delay', 'End delay', 'Card', 'Foul throw-in', 'Punch',
       'Formation change', 'Unknown (ID: 81)', 'Referee Drop Ball',
       'Collection End', 'Keeper Sweeper', 'Claim', 'Unknown (ID: 80)',
       'Condition change', 'Smother', 'Unknown (ID: 84)',
       'Contentious referee decision', 'Penalty faced',
       'Cross not claimed', 'Good Skill', 'Player retired',
       'Chance missed'], dtype=object)

In [17]:
df_events[
    (df_events["type_name"] == "Save")
    & (df_events["player_id"] == "398isvyux7zpjiwa2hzsxyc16")
]

,id,match_id,type_id,type_name,period_id,minute,second,team_id,player_id,player_name,outcome,x,y,timestamp
749,2886960301,32tmyy818d2gsssvn24xizwno,10,Save,1,40,48,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,0.7,44.9,2025-12-30 20:56:08.793000+00:00
751,2886960271,32tmyy818d2gsssvn24xizwno,10,Save,1,40,49,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.4,49.5,2025-12-30 20:56:10.366000+00:00
1157,2886973421,32tmyy818d2gsssvn24xizwno,10,Save,2,63,4,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.7,47.6,2025-12-30 21:34:36.132000+00:00
2674,2887597119,36sm5uwycnu4y21bqg6fdnc44,10,Save,2,50,47,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,0.6,55.3,2026-01-04 13:37:42.775000+00:00
2966,2887602439,36sm5uwycnu4y21bqg6fdnc44,10,Save,2,69,27,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.7,50.3,2026-01-04 13:56:22.262000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57078,2930496079,4s4lfi1tj69ftoawrdig1erys,10,Save,1,16,33,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,4.6,43.0,2026-04-27 19:16:48.540000+00:00
57131,2930498117,4s4lfi1tj69ftoawrdig1erys,10,Save,1,19,39,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,2.2,49.3,2026-04-27 19:19:54.707000+00:00
57452,2930507315,4s4lfi1tj69ftoawrdig1erys,10,Save,1,36,0,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,3.9,50.2,2026-04-27 19:36:15.475000+00:00
57486,2930508459,4s4lfi1tj69ftoawrdig1erys,10,Save,1,38,6,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,2.3,46.4,2026-04-27 19:38:21.603000+00:00
58433,2930543823,4s4lfi1tj69ftoawrdig1erys,10,Save,2,89,28,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,3.4,53.9,2026-04-27 20:47:09.175000+00:00

In [18]:
df_events.iloc[746:750]

,id,match_id,type_id,type_name,period_id,minute,second,team_id,player_id,player_name,outcome,x,y,timestamp
746,2886960227,32tmyy818d2gsssvn24xizwno,1,Pass,1,40,40,b9si1jn1lfxfund69e9ogcu2n,970owquiv1ukwfm4fn89gc7pw,M. Mané,1,47.9,30.3,2025-12-30 20:56:01.510000+00:00
747,2886960263,32tmyy818d2gsssvn24xizwno,1,Pass,1,40,45,b9si1jn1lfxfund69e9ogcu2n,boehs62sf23wlas5wb4l5s2y,T. Arokodare,1,85.8,65.8,2025-12-30 20:56:05.894000+00:00
748,2886960265,32tmyy818d2gsssvn24xizwno,15,Attempt Saved,1,40,48,b9si1jn1lfxfund69e9ogcu2n,f1lellpt59ka10kyngi7vsqy2,Hugo Bueno,1,95.5,65.7,2025-12-30 20:56:08.693000+00:00
749,2886960301,32tmyy818d2gsssvn24xizwno,10,Save,1,40,48,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,0.7,44.9,2025-12-30 20:56:08.793000+00:00

In [19]:
df_qualifiers = pd.read_parquet("../data/match-events/qualifiers.parquet")

In [20]:
df_qualifiers.shape

(276047, 5)

In [21]:
df_qualifiers[df_qualifiers["event_id"].isin([2886960265,2886960301])]

,event_id,qualifier_id,qualifier_name,qualifier_desc,value
3601,2886960265,233,Unknown (ID: 233),No description,396
3602,2886960265,154,Intentional assist,Intentional assist,None
3603,2886960265,146,Unknown (ID: 146),No description,99.3
3604,2886960265,65,Unknown (ID: 65),No description,None
3605,2886960265,29,Assisted,Shot had assist,None
3606,2886960265,103,Unknown (ID: 103),No description,1.3
3607,2886960265,102,Unknown (ID: 102),No description,50.1
3608,2886960265,78,Unknown (ID: 78),No description,None
3609,2886960265,56,Zone,Back/Left/Centre/Right,Center
3610,2886960265,147,Unknown (ID: 147),No description,54.9
3611,2886960265,328,Unknown (ID: 328),No description,None
3612,2886960265,55,Unknown (ID: 55),No description,342
3613,2886960265,72,Left footed,Shot with left foot,None
3614,2886960265,22,Unknown (ID: 22),No description,None
3615,2886960301,183,Feet,GK saves with feet,None
3616,2886960301,233,Unknown (ID: 233),No description,343
3617,2886960301,173,Parried safe,GK parries safe,None
3618,2886960301,376,Unknown (ID: 376),No description,None
3619,2886960301,180,Stooping,GK stooping save,None
3620,2886960301,56,Zone,Back/Left/Centre/Right,Back

In [22]:
df_events[df_events["type_name"].str.startswith("Unknown")]["type_name"].unique()

array(['Unknown (ID: 83)', 'Unknown (ID: 81)', 'Unknown (ID: 80)',
       'Unknown (ID: 84)'], dtype=object)

In [23]:
df_qualifiers[df_qualifiers["qualifier_name"].str.startswith("Unknown")][
    "qualifier_name"
].unique()

array(['Unknown (ID: 127)', 'Unknown (ID: 399)', 'Unknown (ID: 13)',
       'Unknown (ID: 294)', 'Unknown (ID: 233)', 'Unknown (ID: 286)',
       'Unknown (ID: 285)', 'Unknown (ID: 467)', 'Unknown (ID: 465)',
       'Unknown (ID: 167)', 'Unknown (ID: 73)', 'Unknown (ID: 75)',
       'Unknown (ID: 464)', 'Unknown (ID: 211)', 'Unknown (ID: 383)',
       'Unknown (ID: 385)', 'Unknown (ID: 389)', 'Unknown (ID: 347)',
       'Unknown (ID: 346)', 'Unknown (ID: 103)', 'Unknown (ID: 64)',
       'Unknown (ID: 102)', 'Unknown (ID: 55)', 'Unknown (ID: 22)',
       'Unknown (ID: 361)', 'Unknown (ID: 74)', 'Unknown (ID: 384)',
       'Unknown (ID: 377)', 'Unknown (ID: 17)', 'Unknown (ID: 458)',
       'Unknown (ID: 295)', 'Unknown (ID: 378)', 'Unknown (ID: 170)',
       'Unknown (ID: 396)', 'Unknown (ID: 78)', 'Unknown (ID: 468)',
       'Unknown (ID: 395)', 'Unknown (ID: 374)', 'Unknown (ID: 375)',
       'Unknown (ID: 18)', 'Unknown (ID: 386)', 'Unknown (ID: 185)',
       'Unknown (ID: 328)', 'Unknown (ID: 146)', 'Unknown (ID: 147)',
       'Unknown (ID: 87)', 'Unknown (ID: 24)', 'Unknown (ID: 82)',
       'Unknown (ID: 76)', 'Unknown (ID: 94)', 'Unknown (ID: 25)',
       'Unknown (ID: 61)', 'Unknown (ID: 85)', 'Unknown (ID: 65)',
       'Unknown (ID: 376)', 'Unknown (ID: 80)', 'Unknown (ID: 472)',
       'Unknown (ID: 277)', 'Unknown (ID: 293)', 'Unknown (ID: 145)',
       'Unknown (ID: 292)', 'Unknown (ID: 345)', 'Unknown (ID: 77)',
       'Unknown (ID: 488)', 'Unknown (ID: 362)', 'Unknown (ID: 84)',
       'Unknown (ID: 16)', 'Unknown (ID: 252)', 'Unknown (ID: 79)',
       'Unknown (ID: 380)', 'Unknown (ID: 354)', 'Unknown (ID: 391)',
       'Unknown (ID: 81)', 'Unknown (ID: 387)', 'Unknown (ID: 393)',
       'Unknown (ID: 229)', 'Unknown (ID: 302)', 'Unknown (ID: 23)',
       'Unknown (ID: 70)', 'Unknown (ID: 63)', 'Unknown (ID: 392)',
       'Unknown (ID: 100)', 'Unknown (ID: 62)', 'Unknown (ID: 83)',
       'Unknown (ID: 397)', 'Unknown (ID: 363)', 'Unknown (ID: 49)',
       'Unknown (ID: 46)', 'Unknown (ID: 47)', 'Unknown (ID: 232)',
       'Unknown (ID: 10)', 'Unknown (ID: 101)', 'Unknown (ID: 14)',
       'Unknown (ID: 66)', 'Unknown (ID: 169)', 'Unknown (ID: 60)',
       'Unknown (ID: 319)', 'Unknown (ID: 300)', 'Unknown (ID: 26)',
       'Unknown (ID: 239)', 'Unknown (ID: 343)', 'Unknown (ID: 216)',
       'Unknown (ID: 436)', 'Unknown (ID: 364)', 'Unknown (ID: 329)',
       'Unknown (ID: 365)', 'Unknown (ID: 336)', 'Unknown (ID: 484)',
       'Unknown (ID: 314)', 'Unknown (ID: 298)', 'Unknown (ID: 19)',
       'Unknown (ID: 381)', 'Unknown (ID: 398)', 'Unknown (ID: 348)',
       'Unknown (ID: 331)', 'Unknown (ID: 390)', 'Unknown (ID: 353)',
       'Unknown (ID: 459)', 'Unknown (ID: 330)', 'Unknown (ID: 86)',
       'Unknown (ID: 276)', 'Unknown (ID: 249)', 'Unknown (ID: 250)',
       'Unknown (ID: 485)', 'Unknown (ID: 190)', 'Unknown (ID: 388)',
       'Unknown (ID: 68)', 'Unknown (ID: 297)', 'Unknown (ID: 490)',
       'Unknown (ID: 12)', 'Unknown (ID: 335)', 'Unknown (ID: 474)',
       'Unknown (ID: 296)', 'Unknown (ID: 332)'], dtype=object)