In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from mplsoccer import Pitch

In [2]:
matches = pd.read_parquet("../data/match-events/metadata.parquet")

In [4]:
matches[["local_date", "home_team_name", "away_team_name"]].sort_values(by="local_date")

    local_date           home_team_name           away_team_name
5   2025-08-17        Manchester United                  Arsenal
6   2025-08-24                   Fulham        Manchester United
7   2025-08-30        Manchester United                  Burnley
8   2025-09-14          Manchester City        Manchester United
9   2025-09-20        Manchester United                  Chelsea
10  2025-09-27                Brentford        Manchester United
11  2025-10-04        Manchester United               Sunderland
12  2025-10-19                Liverpool        Manchester United
13  2025-10-25        Manchester United   Brighton & Hove Albion
14  2025-11-01        Nottingham Forest        Manchester United
15  2025-11-08        Tottenham Hotspur        Manchester United
16  2025-11-24        Manchester United                  Everton
17  2025-11-30           Crystal Palace        Manchester United
18  2025-12-04        Manchester United          West Ham United
19  2025-12-08  Wolverhampton Wanderers        Manchester United
20  2025-12-15        Manchester United          AFC Bournemouth
21  2025-12-21              Aston Villa        Manchester United
22  2025-12-26        Manchester United         Newcastle United
0   2025-12-30        Manchester United  Wolverhampton Wanderers
1   2026-01-04             Leeds United        Manchester United
2   2026-01-07                  Burnley        Manchester United
3   2026-01-17        Manchester United          Manchester City
4   2026-01-25                  Arsenal        Manchester United
23  2026-02-01        Manchester United                   Fulham

In [2]:
df_events = pd.read_parquet("../data/match-events/events.parquet")

In [8]:
df_events["type_name"].unique()

array(['Team set up', 'Start', 'Pass', 'Ball touch', 'Unknown (ID: 83)',
       'Clearance', 'Ball recovery', 'Foul', 'Take On', 'Deleted event',
       'Corner Awarded', 'Aerial', 'Challenge', 'Interception', 'Tackle',
       'Out', 'Blocked Pass', 'Dispossessed', 'Miss', 'Keeper pick-up',
       'Offside Pass', 'Offside provoked', 'Shield ball opp', 'Error',
       'Goal', 'Attempt Saved', 'Save', 'Post',
       'Injury Time Announcement', 'End', 'Player off', 'Player on',
       'Start delay', 'End delay', 'Card', 'Foul throw-in', 'Punch',
       'Formation change', 'Unknown (ID: 81)', 'Referee Drop Ball',
       'Collection End', 'Keeper Sweeper', 'Claim', 'Unknown (ID: 80)',
       'Condition change', 'Smother', 'Unknown (ID: 84)',
       'Contentious referee decision', 'Penalty faced',
       'Cross not claimed', 'Good Skill', 'Player retired'], dtype=object)

In [4]:
df_events[
    (df_events["type_name"] == "Save")
    & (df_events["player_id"] == "398isvyux7zpjiwa2hzsxyc16")
]

,id,match_id,type_id,type_name,period_id,minute,second,team_id,player_id,player_name,outcome,x,y,timestamp
749,2886960301,32tmyy818d2gsssvn24xizwno,10,Save,1,40,48,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,0.7,44.9,2025-12-30 20:56:08.793000+00:00
751,2886960271,32tmyy818d2gsssvn24xizwno,10,Save,1,40,49,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.4,49.5,2025-12-30 20:56:10.366000+00:00
1157,2886973421,32tmyy818d2gsssvn24xizwno,10,Save,2,63,4,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.7,47.6,2025-12-30 21:34:36.132000+00:00
2674,2887597119,36sm5uwycnu4y21bqg6fdnc44,10,Save,2,50,47,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,0.6,55.3,2026-01-04 13:37:42.775000+00:00
2966,2887602439,36sm5uwycnu4y21bqg6fdnc44,10,Save,2,69,27,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.7,50.3,2026-01-04 13:56:22.262000+00:00
5863,2889997787,3euckq6g15mkb2d6jes5yi68k,10,Save,1,36,7,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.8,52.1,2026-01-17 13:06:32.306000+00:00
7270,2892932773,3h7uw06wrdggi4gvmvcm40xlg,10,Save,1,17,47,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.6,51.0,2026-01-25 16:47:55.372000+00:00
8107,2892991319,3h7uw06wrdggi4gvmvcm40xlg,10,Save,2,70,27,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.0,50.7,2026-01-25 17:58:10.749000+00:00
8297,2893000747,3h7uw06wrdggi4gvmvcm40xlg,10,Save,2,82,35,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.1,53.0,2026-01-25 18:10:19.322000+00:00
19082,2855560309,1qvclot8fak9knempsk7tqeqc,10,Save,1,32,2,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,2.1,49.8,2025-10-04 14:32:45.664000+00:00
19278,2855587815,1qvclot8fak9knempsk7tqeqc,10,Save,1,43,11,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.2,54.1,2025-10-04 14:43:54.615000+00:00
20165,2855714665,1qvclot8fak9knempsk7tqeqc,10,Save,2,89,53,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,3.9,44.2,2025-10-04 15:52:36.612000+00:00
20658,2861495139,1tozdgn4jg7t4h8wrdqtlwgt0,10,Save,1,25,37,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,3.5,48.6,2025-10-19 15:55:57.714000+00:00
20779,2861501749,1tozdgn4jg7t4h8wrdqtlwgt0,10,Save,1,32,12,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.2,53.4,2025-10-19 16:02:32.912000+00:00
20829,2861503809,1tozdgn4jg7t4h8wrdqtlwgt0,10,Save,1,34,13,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,2.1,53.9,2025-10-19 16:04:33.807000+00:00
20883,2861508379,1tozdgn4jg7t4h8wrdqtlwgt0,10,Save,1,38,26,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.7,43.2,2025-10-19 16:08:46.238000+00:00
21553,2861566969,1tozdgn4jg7t4h8wrdqtlwgt0,10,Save,2,75,9,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.9,47.3,2025-10-19 17:05:27.946000+00:00
22241,2864009069,1z0pvc6kf8t3einy25wvna42c,10,Save,1,14,14,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.4,47.8,2025-10-25 16:45:07.843000+00:00
23371,2864090069,1z0pvc6kf8t3einy25wvna42c,10,Save,2,74,33,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.4,49.0,2025-10-25 18:02:37.389000+00:00
23675,2864104261,1z0pvc6kf8t3einy25wvna42c,10,Save,2,87,34,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.8,47.3,2025-10-25 18:15:38.427000+00:00
23995,2867215855,22l2npjyvz69z79ahof2wafpw,10,Save,1,7,10,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,2.1,52.1,2025-11-01 15:07:46.190000+00:00
26570,2870508545,27dsai0y163f2lmufao3yg3ys,10,Save,2,53,30,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.5,49.2,2025-11-08 13:41:10.158000+00:00
26592,2870510923,27dsai0y163f2lmufao3yg3ys,10,Save,2,55,16,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.7,49.5,2025-11-08 13:42:56.214000+00:00
27206,2870549155,27dsai0y163f2lmufao3yg3ys,10,Save,2,88,58,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.2,54.6,2025-11-08 14:16:38.019000+00:00
29340,2878373609,2ddgt0wgk8212ask4bgjokqac,10,Save,1,12,33,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,2.8,50.1,2025-11-30 12:13:06.286000+00:00
29525,2878377495,2ddgt0wgk8212ask4bgjokqac,10,Save,1,23,36,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,2.6,50.1,2025-11-30 12:24:09.151000+00:00
31427,2879866797,2j3cj5hutmxhlj7ggvbwzi0ic,10,Save,1,34,22,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,2.5,51.4,2025-12-04 20:34:29.955000+00:00
33843,2881638577,2ntyu72wz8vu95ocn09cwlmok,10,Save,2,70,19,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.7,46.5,2025-12-08 21:29:09.628000+00:00
34798,2883761683,2qnbwtbl7eh08dh64ii9icqac,10,Save,1,28,30,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,3.3,48.2,2025-12-15 20:28:50.173000+00:00
35042,2883767619,2qnbwtbl7eh08dh64ii9icqac,10,Save,1,44,28,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.7,52.8,2025-12-15 20:44:48.314000+00:00
35878,2883791047,2qnbwtbl7eh08dh64ii9icqac,10,Save,2,95,29,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,2.2,51.0,2025-12-15 21:56:39.863000+00:00
35891,2883791375,2qnbwtbl7eh08dh64ii9icqac,10,Save,2,97,18,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,3.6,53.7,2025-12-15 21:58:29.303000+00:00
35930,2883791907,2qnbwtbl7eh08dh64ii9icqac,10,Save,2,99,34,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,2.5,53.4,2025-12-15 22:00:44.390000+00:00
36095,2885428583,2sqsn3aeeuy6wzu7i0d7xxbmc,10,Save,1,6,56,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,2.4,52.1,2025-12-21 16:38:16.609000+00:00
36484,2885451571,2sqsn3aeeuy6wzu7i0d7xxbmc,10,Save,1,32,26,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,2.8,49.9,2025-12-21 17:03:45.880000+00:00
37783,2886294889,2yuulrtp37mbqe9rok936lslw,10,Save,1,12,0,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,0.7,46.8,2025-12-26 20:12:26.508000+00:00
39090,2886302697,2yuulrtp37mbqe9rok936lslw,10,Save,2,79,3,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.8,47.6,2025-12-26 21:38:12.191000+00:00
39308,2886304199,2yuulrtp37mbqe9rok936lslw,10,Save,2,91,8,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,2.1,51.9,2025-12-26 21:50:16.899000+00:00
39677,2895341759,3mupduyj99i9jq4xrg9rneoes,10,Save,1,12,40,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,0.9,45.6,2026-02-01 14:12:55.569000+00:00
40133,2895374917,3mupduyj99i9jq4xrg9rneoes,10,Save,1,39,15,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.7,49.0,2026-02-01 14:39:30.699000+00:00
40377,2895403643,3mupduyj99i9jq4xrg9rneoes,10,Save,2,51,2,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.5,50.7,2026-02-01 15:10:54.815000+00:00
40854,2895445729,3mupduyj99i9jq4xrg9rneoes,10,Save,2,80,46,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,1.8,47.4,2026-02-01 15:40:39.054000+00:00

In [7]:
df_events.iloc[746:750]

,id,match_id,type_id,type_name,period_id,minute,second,team_id,player_id,player_name,outcome,x,y,timestamp
746,2886960227,32tmyy818d2gsssvn24xizwno,1,Pass,1,40,40,b9si1jn1lfxfund69e9ogcu2n,970owquiv1ukwfm4fn89gc7pw,M. Mané,1,47.9,30.3,2025-12-30 20:56:01.510000+00:00
747,2886960263,32tmyy818d2gsssvn24xizwno,1,Pass,1,40,45,b9si1jn1lfxfund69e9ogcu2n,boehs62sf23wlas5wb4l5s2y,T. Arokodare,1,85.8,65.8,2025-12-30 20:56:05.894000+00:00
748,2886960265,32tmyy818d2gsssvn24xizwno,15,Attempt Saved,1,40,48,b9si1jn1lfxfund69e9ogcu2n,f1lellpt59ka10kyngi7vsqy2,Hugo Bueno,1,95.5,65.7,2025-12-30 20:56:08.693000+00:00
749,2886960301,32tmyy818d2gsssvn24xizwno,10,Save,1,40,48,6eqit8ye8aomdsrrq0hk3v7gh,398isvyux7zpjiwa2hzsxyc16,S. Lammens,1,0.7,44.9,2025-12-30 20:56:08.793000+00:00

In [9]:
df_qualifiers = pd.read_parquet("../data/match-events/qualifiers.parquet")

In [16]:
df_qualifiers[df_qualifiers["event_id"].isin([2886960265,2886960301])]

,event_id,qualifier_id,qualifier_name,qualifier_desc,value
3601,2886960265,233,Unknown (ID: 233),No description,396
3602,2886960265,154,Intentional assist,Intentional assist,None
3603,2886960265,146,Unknown (ID: 146),No description,99.3
3604,2886960265,65,Unknown (ID: 65),No description,None
3605,2886960265,29,Assisted,Shot had assist,None
3606,2886960265,103,Unknown (ID: 103),No description,1.3
3607,2886960265,102,Unknown (ID: 102),No description,50.1
3608,2886960265,78,Unknown (ID: 78),No description,None
3609,2886960265,56,Zone,Back/Left/Centre/Right,Center
3610,2886960265,147,Unknown (ID: 147),No description,54.9
3611,2886960265,328,Unknown (ID: 328),No description,None
3612,2886960265,55,Unknown (ID: 55),No description,342
3613,2886960265,72,Left footed,Shot with left foot,None
3614,2886960265,22,Unknown (ID: 22),No description,None
3615,2886960301,183,Feet,GK saves with feet,None
3616,2886960301,233,Unknown (ID: 233),No description,343
3617,2886960301,173,Parried safe,GK parries safe,None
3618,2886960301,376,Unknown (ID: 376),No description,None
3619,2886960301,180,Stooping,GK stooping save,None
3620,2886960301,56,Zone,Back/Left/Centre/Right,Back

In [24]:
df_events[df_events["type_name"].str.startswith("Unknown")]["type_name"].unique()

array(['Unknown (ID: 83)', 'Unknown (ID: 81)', 'Unknown (ID: 80)',
       'Unknown (ID: 84)'], dtype=object)

In [26]:
df_qualifiers[df_qualifiers["qualifier_name"].str.startswith("Unknown")][
    "qualifier_name"
].unique()

array(['Unknown (ID: 127)', 'Unknown (ID: 399)', 'Unknown (ID: 13)',
       'Unknown (ID: 294)', 'Unknown (ID: 233)', 'Unknown (ID: 286)',
       'Unknown (ID: 285)', 'Unknown (ID: 467)', 'Unknown (ID: 465)',
       'Unknown (ID: 167)', 'Unknown (ID: 73)', 'Unknown (ID: 75)',
       'Unknown (ID: 464)', 'Unknown (ID: 211)', 'Unknown (ID: 383)',
       'Unknown (ID: 385)', 'Unknown (ID: 389)', 'Unknown (ID: 347)',
       'Unknown (ID: 346)', 'Unknown (ID: 103)', 'Unknown (ID: 64)',
       'Unknown (ID: 102)', 'Unknown (ID: 55)', 'Unknown (ID: 22)',
       'Unknown (ID: 361)', 'Unknown (ID: 74)', 'Unknown (ID: 384)',
       'Unknown (ID: 377)', 'Unknown (ID: 17)', 'Unknown (ID: 458)',
       'Unknown (ID: 295)', 'Unknown (ID: 378)', 'Unknown (ID: 170)',
       'Unknown (ID: 396)', 'Unknown (ID: 78)', 'Unknown (ID: 468)',
       'Unknown (ID: 395)', 'Unknown (ID: 374)', 'Unknown (ID: 375)',
       'Unknown (ID: 18)', 'Unknown (ID: 386)', 'Unknown (ID: 185)',
       'Unknown (ID: 328)', 'Unknown (ID: 146)', 'Unknown (ID: 147)',
       'Unknown (ID: 87)', 'Unknown (ID: 24)', 'Unknown (ID: 82)',
       'Unknown (ID: 76)', 'Unknown (ID: 94)', 'Unknown (ID: 25)',
       'Unknown (ID: 61)', 'Unknown (ID: 85)', 'Unknown (ID: 65)',
       'Unknown (ID: 376)', 'Unknown (ID: 80)', 'Unknown (ID: 472)',
       'Unknown (ID: 277)', 'Unknown (ID: 293)', 'Unknown (ID: 145)',
       'Unknown (ID: 292)', 'Unknown (ID: 345)', 'Unknown (ID: 77)',
       'Unknown (ID: 488)', 'Unknown (ID: 362)', 'Unknown (ID: 84)',
       'Unknown (ID: 16)', 'Unknown (ID: 252)', 'Unknown (ID: 79)',
       'Unknown (ID: 380)', 'Unknown (ID: 354)', 'Unknown (ID: 391)',
       'Unknown (ID: 81)', 'Unknown (ID: 387)', 'Unknown (ID: 393)',
       'Unknown (ID: 229)', 'Unknown (ID: 302)', 'Unknown (ID: 23)',
       'Unknown (ID: 70)', 'Unknown (ID: 63)', 'Unknown (ID: 392)',
       'Unknown (ID: 100)', 'Unknown (ID: 62)', 'Unknown (ID: 83)',
       'Unknown (ID: 397)', 'Unknown (ID: 363)', 'Unknown (ID: 49)',
       'Unknown (ID: 46)', 'Unknown (ID: 47)', 'Unknown (ID: 232)',
       'Unknown (ID: 10)', 'Unknown (ID: 101)', 'Unknown (ID: 14)',
       'Unknown (ID: 66)', 'Unknown (ID: 169)', 'Unknown (ID: 60)',
       'Unknown (ID: 319)', 'Unknown (ID: 300)', 'Unknown (ID: 26)',
       'Unknown (ID: 239)', 'Unknown (ID: 343)', 'Unknown (ID: 216)',
       'Unknown (ID: 436)', 'Unknown (ID: 364)', 'Unknown (ID: 329)',
       'Unknown (ID: 365)', 'Unknown (ID: 336)', 'Unknown (ID: 484)',
       'Unknown (ID: 314)', 'Unknown (ID: 298)', 'Unknown (ID: 19)',
       'Unknown (ID: 381)', 'Unknown (ID: 398)', 'Unknown (ID: 348)',
       'Unknown (ID: 331)', 'Unknown (ID: 390)', 'Unknown (ID: 353)',
       'Unknown (ID: 459)', 'Unknown (ID: 330)', 'Unknown (ID: 86)',
       'Unknown (ID: 276)', 'Unknown (ID: 249)', 'Unknown (ID: 250)',
       'Unknown (ID: 485)', 'Unknown (ID: 190)', 'Unknown (ID: 388)',
       'Unknown (ID: 68)', 'Unknown (ID: 297)'], dtype=object)